version: '3'
services:
  oracle:
    image: pkoperek/baselinesme:2020-06-10
# Configuration for enabling LSTM policies
    environment:
      - POLICY_PATH=/srv/prod_policy/20200609_3_model.bin
      - NETWORK_TYPE=lstm
#    volumes:
#      - ./output_model:/srv/prod_policy
    ports:
      - 8888:8080
